### ISSUE TITLE
2.8  I Install the zip , the addons appear the list . But I cannot found tools,  tools not Capsule tab

### ISSUE THREAD

**Issue by pilotchiao** [Takanu/GEX#16]
2.8  I Install the zip , the addons appear the list . But I cannot found tools,  tools not Capsule tab

cannot appear tools pannel.

**Comment by pilotchiao** [comment]
I found they location ..Thank you ... it's  under View Tab..  Thankyou

**Comment by mcolinp** [comment]
I have the same problem, but I do not see the tools in the 'View' panel (n hotkey).

I was able to see the plugin load (v1.07); and tick the checkbox next to it in 2.81. I cannot find any tools or buttons added after doing this though. 

I tried to load the v1.10_beta; and I cannot get it to show up in the installed plugins list to turn it on. 
I also tried renaming the folder inside the addons directory; since I noticed that there was a '.' in the folder name. (Which seems to cause problems lately for many python scripts.)
