### ISSUE TITLE
Issue/Feature Request: Export of Instanced Collections

### ISSUE THREAD

**Issue by PlasmaErnst** [Takanu/GEX#26]
Hi! Part of my workflow is to create details in collections and then instance these collections and use them to add details to larger meshes. 
However, from my experience when exporting collections containing instanced collections with capsule, those instanced collections don't get exported (I assume because they are not real geometry but instances?). 
It would be great if you can find a way to implement the option to export instanced collections as well.
Thank you for your work!

**Comment by Takanu** [comment]
I have a similar workflow issue when using Geometry Nodes and I currently use a little Python script inside Blender's Text Editor that will realize instances for me before exporting.

While in the future id like the ability for people to be able to insert their own scene changes before export I currently don't accept specific workflow requests to Capsule because in part it's difficult for me to find the time to maintain this plugin on it's own.

You might find my python script useful though, you may have to poke at it a little for your specific purposes but the script should realize any instances in a selected collection, add them to a collection inside it, and export it with Capsule.


[Export Instance Layer with Capsule.zip](https://github.com/Takanu/Capsule/files/8236841/Export.Instance.Layer.with.Capsule.zip)
