### ISSUE TITLE
Compatability issues with Blender versions 3.2 - 3.3

### ISSUE THREAD

**Issue by MattGraczyk** [Takanu/GEX#38]
I've experienced some issues with Capsule supporting any newer build than 3.2.2.

I'm not 100% sure as to the offical support, as the readme states that 3.2 is supported and says nothing about 3.3.

The problem I found is that any version of capsule newer than 1.3.0 does not install correctly into the programs addons folders, or does but does not run and doesn't throw any errors.

I can provide any info if needed but I can't figure out if it's just an incompatibility or if there's an actual bug here. I would expect 1.3.5 to work with Blender 3.2 but so far I haven't been able to make it do so.

Thanks!

**Comment by Takanu** [comment]
Hey, just to double-check are you unzipping the download first, then zipping the Capsule folder inside?  Releases contain extra files not related to the addon and it wont install if you just give Blender the downloaded release ZIP

If youve done this and it still doesn't work your next best bet is to dig into Blender's data folder and manually remove any trace of Capsule to ensure it is uninstalled before reinstalling it.

On Windows it should be inside the AppData/Local folder inside your user folder, on macOS I would guess its located in ~/Library.  Go into the Blender folder until you find an addons folder, then locate and delete Capsule.

**Comment by Takanu** [comment]
Also one more thing as I was reading this again - if you plan on using 3.3 please make sure you use the latest version.  Using an old one won't stop you from installing it but it will potentially cause you problems when trying to export due to the API differences.

**Comment by MattGraczyk** [comment]
Ohhh I missed the unzip procedure or had forgotten since I last installed it. That fixed my issue it looks like.

Thanks for the quick assistance, I need to remember to re-read installation instructions.

While I have you as well, is there a way to make export file locations support relative paths? Sharing asset files among our team is becoming a bit of a pain since our export locations are unique to the local P4 repos.

**Comment by Takanu** [comment]
There is, just make sure when selecting the path for a File Location that you click on the gear icon and select, "Relative Path"
![image](https://user-images.githubusercontent.com/9108903/190636427-c18618f6-2dad-4b4b-ba72-79056a705765.png)

**Be careful when using Relative Paths**, unlike Absolute Paths if the directory doesn't exist or has changed an error will appear.  This error has been rewritten recently in an unreleased version to account for this behavior but if you see the error, "The File Location points to a file rather than a directory" and you're using Relative Paths it's likely that the directory structure has changed and that you'll need to reassign the Location path.
