### ISSUE TITLE
Error exporting glTF

### ISSUE THREAD

**Issue by Inkdependence** [Takanu/GEX#41]
Hi,
I'm always have some type of error when I try to export in glTF format.
Tested in Blender 3.3 and Blender 3.4, last version of Capsule. Tried in a fresh Blender installation too., and changing a lot of options (static, animated, applying modifiers or not, 3 diferent glTF formats, etc)
Exporting in fbx works like a charm, as usual, but in glTF I always have the same problem.
Exporting using the Blender glTF exporter works.
¿any idea?
Thanks in advance!

![x2scrap](https://user-images.githubusercontent.com/28936800/208959197-37597ae7-9926-4283-9efa-126e629b4122.png)

**Comment by Takanu** [comment]
Hey, can you check the master version of Capsule?  I use GLTF on a daily basis and I thought this issue was fixed, but it might be because ive yet to push an update.

**Comment by Inkdependence** [comment]
Checked the master branch version (removing the previous version) and same result :(

**Comment by Takanu** [comment]
Thanks for trying it out, I will look into it as soon as I can (hopefully Saturday) and post a fix as this looks like a simple API update issue.

**Comment by Takanu** [comment]
Hey, i looked into this in more detail and the current master version definitely fixed this issue - there might be a chance this is caused by an old Export Preset storing a property that the GLTF exporter no longer recognizes.  Delete your GLTF export preset and create a new one, then try again.

I recently published what was in the master as a new version so make sure to try that one out.

**Comment by Inkdependence** [comment]
Hey!
Sorry for the delay!
Tested right now and is working again like a charm (Blender 3.4, clean installation) :)
Thank you very much for your support!
