### ISSUE TITLE
Question about rotation

### ISSUE THREAD

**Issue by guategeek** [Takanu/GEX#42]
Hi first off I appreciate this plugin so much, thanks for making it, sharing it and keeping it working on new versions of blender.

I have been blocking out a level in blender and now I'm working on using capsule to export to Unreal and have the level block-out there. Today for the first time I exported a mesh that has rotation in blender, I was expecting it to show up with no rotated in Unreal. But what is actually happening is its showing up in Unreal with what looks like the rotation applied (rotated but no rotation values).

![image](https://user-images.githubusercontent.com/868801/211688493-c0adf383-e15f-4eb8-b47a-4c064111aac3.png)

I would like the mesh to export from Blender with the rotation removed, so that I can use it like an actor/prefab in engine and rotate it as I wish there. Much like Capsule can export each object using its own origin point. Is there any way to do this with Capsule right now? I looked through all the FBX options and didn't see anything that would be applying the rotation, in case it was something in there.

**Comment by Takanu** [comment]
Hey, I can only hypothesize whats happening as I only use Unity 2019 at the moment.  It's important to note that the Capsule addon doesn't provide it's own unique export scripts and relies on the exporters built into Blender, 

First, **make sure Bake Space Transform is unticked** as that will apply object transforms during export.

If it is you should then **try exporting without Capsule to see if the problem is fixed.**
If not using Capsule fixes the issue then let me know as it might be a bug with my addon 👍

**Comment by guategeek** [comment]
Ah ok, thanks for the info. I have played with the export settings and capsule and blender export the same.

I realize that what I was hoping that capsule would do was have an option to strip rotation on export, sort of like how you can export each object centered at 0,0. So that if I had the object rotated 45 degrees in my blender scene the exported object would be un-rotated. But I realize now that would have to be a separate step that would run before the main export.

**Comment by Takanu** [comment]
It's something Capsule could potentially do but i'd rather let people handle that with a Pack Scripts feature I'm working on instead of offering it as a separate option.  Regardless i'll keep this in mind for future updates.
