### ISSUE TITLE
Custom Normals don't export

### ISSUE THREAD

**Issue by Michaelknubben** [Takanu/GEX#6]
As referenced here: https://blenderartists.org/forum/showthread.php?397963-Addon-Capsule-1-06-One-Click-Batch-FBX-Exports&p=3197606&viewfull=1#post3197606

"When I export with the regular FBX exporter (7.4, default settings), Unity imports my custom normals perfectly. When I export through Capsule, it doesn't. Settings are the same as far as I can see, certainly 'Only Normals' is checked. "

"I'm having some problems with my meshes averaged normals when exported with your addon.
I assume it has to do with the FBX version, Im using 7.4 binary.
To reproduce the error, try adjusting your meshes normals using this one:
https://github.com/fedackb/yavne
I dont know if its related to that. "

I reported this in the thread and through email, but I didn't see it on here (and the email about the new update didn't mention it either), so I'm submitting it here as well.

**Comment by Takanu** [comment]
Capsule is just a wrapper that uses the in-built FBX exporter, so it "should" work unless it's using a modifier, as during the export process it'll disable or switch off certain things in order to prepare the export.  

I'm currently at the end of updating the code for 1.1 and i'll definitely make sure to review this problem once done 👌
